"""add image variants

Revision ID: 93c9caa0ad8d
Revises: 0c440f5d5659
Create Date: 2026-02-21 07:15:56.417928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c9caa0ad8d'
down_revision: Union[str, Sequence[str], None] = '0c440f5d5659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_variants', sa.Column('file_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_variants', 'file_path')
    # ### end Alembic commands ###
