"""file_path

Revision ID: 9e9f5e50bd6b
Revises: 3443421d04b3
Create Date: 2026-02-12 09:54:26.250576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9f5e50bd6b'
down_revision: Union[str, Sequence[str], None] = '3443421d04b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_path', sa.String(), nullable=False))
    op.drop_column('images', 'filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('filepath', sa.VARCHAR(), nullable=False))
    op.drop_column('images', 'file_path')
    # ### end Alembic commands ###
